version: "3.8"

services:
  dashoboard:
    container_name: admin-dashoboard
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - chatbot
    restart: always

networks:
  chatbot:
    external: true
      