apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-env
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "NEXT_PUBLIC_API_ENDPOINT"
        objectType: "ssmparameter"
      - objectName: "NEXT_PUBLIC_BASE_URL"
        objectType: "ssmparameter"
      - objectName: "NEXT_PUBLIC_SERVER_URL"
        objectType: "ssmparameter"
      - objectName: "NEXTAUTH_SECRET"
        objectType: "ssmparameter"