name: CI - Chatbot Admin Dashboard pipeline

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - devops
  # pull_request:
  #   branches:
  #     - main
env:
  ACTIONS_RUNNER_DEBUG: true
  AWS_REGION: ap-southeast-1
  AWS_ACCOUNT_ID: 212945523191
  AWS_ECR_REPO: 212945523191.dkr.ecr.ap-southeast-1.amazonaws.com/chatbot-app/admin-dashboard

permissions:
  id-token: write
  contents: write
  security-events: write
  actions: read
  pull-requests: write 

jobs:
  # scan:
  #   name: gitleaks
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #         ref: devops
  #     - uses: gitleaks/gitleaks-action@v2
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    #needs: scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
        with:
          #role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-oidc-role
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ai-competency/chatbot-admin-dashboard
          #IMAGE_TAG: ${{ github.sha }}
          #IMAGE_TAG: ${{ github.run_number }}
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Generate imagedefinitions.json
        run: |
          IMAGE_TAG=latest
          echo '[{"name": "chatbot-admin-dashboar", "imageUri": "905418236735.dkr.ecr.eu-north-1.amazonaws.com/ai-competency/chatbot-admin-dashboard:'"$IMAGE_TAG"'"}]' > imagedefinitions.json

      - name: Upload imagedefinitions.json
        uses: actions/upload-artifact@v4
        with:
          name: imagedefinitions
          path: imagedefinitions.json
